#!/usr/bin/env python3
"""Copy the static component-review viewer into an OUT directory (the site root).

    python3 tools/component-review/viewer/build_site.py --out cr-out [--no-offline]

Copies index.html, viewer.css and js/ next to manifest.json / review.json / items/ that the
render and checks steps wrote. Never modifies those data files. Stdlib only; exits non-zero only
if the build itself fails (a missing manifest.json is reported as a warning, not an error).

Unless --no-offline is given it also makes the site work when opened straight from disk
(file://, e.g. an unzipped GitHub Actions artifact), where browsers block fetch(), ES modules
and workers:
    js/bundle.js        the ES modules as one classic script (plus the STEP worker's source)
    data.js             window.CR_DATA = {manifest, review, texts: {<diff.patch url>: text}}
    offline/<slug>.js   per item, loaded on demand by the 3D view: geometry JSON, layer SVGs and
                        STEP models (base64)
    serve.py            tiny local web server (127.0.0.1, random port) for full http mode
    README.txt          how to open the report
"""
import argparse
import base64
import json
import os
import re
import shutil
import sys
from pathlib import Path
from urllib.parse import quote

HERE = Path(__file__).resolve().parent
FILES = ["index.html", "viewer.css"]
DIRS = ["js"]
DATA_NAMES = {"manifest.json", "review.json", "review.md", "items"}
SLUG_RE = re.compile(r"^[A-Za-z0-9._-]{1,200}$")
MAX_PACK_FILE = 50 * 1024 * 1024  # skip larger single files offline (serve.py still has them)
WORKER = "step_worker.js"
ENTRY = "app.js"


# ─── bundle: ES modules -> one classic script ──────────────────────────────────────────────────

IMPORT_RE = re.compile(r"^import\s*\{([^}]*)\}\s*from\s*['\"](\./[A-Za-z0-9_.-]+\.js)['\"];?[ \t]*$", re.M)
EXPORT_RE = re.compile(r"^export\s+(?:(async\s+)?function\s*\*?\s*([A-Za-z_$][\w$]*)|(const|let|var|class)\s+([A-Za-z_$][\w$]*))", re.M)
DYN_IMPORT_RE = re.compile(r"\bimport\(\s*['\"](\./[A-Za-z0-9_.-]+\.js)['\"]\s*\)")


def transform_module(name: str, src: str) -> str:
    """Body of one module as a function(__exports) for the bundle. Handles the forms the viewer uses
    (named imports from './x.js', `export function|const|let|class`, `import('./x.js')`, import.meta.url)
    and refuses anything else so a new construct can't silently break the file:// build."""
    def imp(m):
        names = []
        for part in m.group(1).split(","):
            part = part.strip()
            if not part:
                continue
            a = re.fullmatch(r"([A-Za-z_$][\w$]*)(?:\s+as\s+([A-Za-z_$][\w$]*))?", part)
            if not a:
                raise ValueError(f"{name}: unsupported import specifier {part!r}")
            names.append(f"{a.group(1)}: {a.group(2)}" if a.group(2) else a.group(1))
        return f"const {{ {', '.join(names)} }} = __require({json.dumps(m.group(2))});"

    body = IMPORT_RE.sub(imp, src)
    exports = []

    def exp(m):
        exports.append(m.group(2) or m.group(4))
        return m.group(0)[len("export"):].lstrip()

    body = EXPORT_RE.sub(exp, body)
    body = DYN_IMPORT_RE.sub(lambda m: f"Promise.resolve().then(() => __require({json.dumps(m.group(1))}))", body)
    body = body.replace("import.meta.url", f"new URL({json.dumps('js/' + name)}, document.baseURI).href")
    leftover = re.search(r"^\s*(import\s|export\s)", body, re.M)
    if leftover:
        line = body[leftover.start():].splitlines()[0]
        raise ValueError(f"{name}: unsupported module syntax for the file:// bundle: {line.strip()!r}")
    tail = f"\n  Object.assign(__exports, {{ {', '.join(exports)} }});" if exports else ""
    return f"__defs[{json.dumps('./' + name)}] = function (__exports) {{\n'use strict';\n{body}{tail}\n}};\n"


def make_bundle(js_dir: Path) -> str:
    parts = ["// Generated by build_site.py from js/*.js for file:// use (classic script, no ES modules).",
             "// Do not edit; edit the modules and rebuild.",
             "(function () {", "'use strict';",
             "const __defs = {};", "const __cache = {};",
             "function __require(n) {",
             "  if (!__cache[n]) { if (!__defs[n]) throw new Error('bundle: no module ' + n);"
             " __cache[n] = {}; __defs[n](__cache[n]); }",
             "  return __cache[n];", "}"]
    for f in sorted(js_dir.glob("*.js")):
        if f.name in (WORKER, "boot.js", "bundle.js"):
            continue
        parts.append(transform_module(f.name, f.read_text(encoding="utf-8")))
    worker_src = (js_dir / WORKER).read_text(encoding="utf-8")
    parts.append(f"window.CR_STEP_WORKER_SRC = {js_literal(worker_src)};")
    parts.append(f"__require({json.dumps('./' + ENTRY)});")
    parts.append("}());")
    return "\n".join(parts) + "\n"


# ─── data.js and per-item packs ─────────────────────────────────────────────────────────────────

def js_literal(value) -> str:
    """JSON that is also safe inside any HTML/JS context: no raw <, >, &, U+2028/9."""
    s = json.dumps(value, ensure_ascii=True, separators=(",", ":"))
    return s.replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")


def asset_url(p: str) -> str:
    """Same encoding as assetUrl() in js/util.js (encodeURIComponent per segment)."""
    return "/".join(quote(seg, safe="!~*'()") for seg in p.split("/"))


def confined_file(out: Path, rel, slug: str | None = None) -> Path | None:
    """out/rel if rel is a plain relative path to a regular file inside out (and inside items/<slug>/
    when slug is given), else None. Manifest paths come from a PR."""
    if not isinstance(rel, str) or not rel or "\\" in rel or "\x00" in rel or rel.startswith("/"):
        return None
    if re.match(r"^[a-z][a-z0-9+.-]*:", rel, re.I) or any(seg in ("", ".", "..") for seg in rel.split("/")):
        return None
    if slug is not None and not rel.startswith(f"items/{slug}/"):
        return None
    base = out.resolve()
    p = (base / rel).resolve()
    if base not in p.parents or not p.is_file():
        return None
    return p


def load_json(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


def item_3d_files(item: dict) -> list[tuple[str, str]]:
    """(path, 'text'|'b64') of everything the 3D view loads for an item."""
    out = []
    for side in ("head", "base"):
        g = (item.get("geom") or {}).get(side) if isinstance(item.get("geom"), dict) else None
        if g:
            out.append((g, "text"))
        layers = ((item.get("renders") or {}).get(side) or {}).get("layers") if isinstance(item.get("renders"), dict) else None
        if isinstance(layers, dict):
            out += [(v, "text") for v in layers.values()]
        models = (item.get("model3d_by_side") or {}).get(side) if isinstance(item.get("model3d_by_side"), dict) else None
        for m in models or []:
            if isinstance(m, dict) and m.get("file"):
                out.append((m["file"], "b64"))
    for m in item.get("model3d") or []:
        if isinstance(m, dict) and m.get("file"):
            out.append((m["file"], "b64"))
    seen, uniq = set(), []
    for p, kind in out:
        if isinstance(p, str) and p not in seen:
            seen.add(p)
            uniq.append((p, kind))
    return uniq


def build_offline(out: Path) -> dict:
    stats = {"data_js": 0, "packs": 0, "pack_bytes": 0, "skipped": []}
    manifest = load_json(out / "manifest.json")
    review = load_json(out / "review.json") if (out / "review.json").is_file() else None
    offline = out / "offline"
    if offline.exists():
        shutil.rmtree(offline)
    if not isinstance(manifest, dict):
        return stats  # the viewer shows its "no data" page
    texts = {}
    items = manifest.get("items") if isinstance(manifest.get("items"), list) else []
    for it in items:
        if not isinstance(it, dict):
            continue
        slug = it.get("slug")
        ok_slug = isinstance(slug, str) and SLUG_RE.match(slug) and slug not in (".", "..")
        td = it.get("text_diff")
        p = confined_file(out, td)
        if p:
            texts[asset_url(td)] = p.read_text(encoding="utf-8", errors="replace")
        if not ok_slug or it.get("kind") != "footprint":
            continue
        files = {}
        for rel, kind in item_3d_files(it):
            fp = confined_file(out, rel, slug)
            if not fp:
                continue
            if fp.stat().st_size > MAX_PACK_FILE:
                stats["skipped"].append(rel)
                continue
            data = fp.read_bytes()
            files[asset_url(rel)] = ({"text": data.decode("utf-8", errors="replace")} if kind == "text"
                                     else {"b64": base64.b64encode(data).decode("ascii")})
        if files:
            offline.mkdir(exist_ok=True)
            js = (f"// Generated by build_site.py: offline copies of {slug}'s 3D inputs.\n"
                  f"(window.CR_PACKS = window.CR_PACKS || {{}})[{js_literal(slug)}] = {js_literal({'files': files})};\n")
            (offline / f"{slug}.js").write_text(js, encoding="ascii")
            stats["packs"] += 1
            stats["pack_bytes"] += len(js)
    data_js = (f"// Generated by build_site.py: report data for file:// use.\n"
               f"window.CR_DATA = {js_literal({'manifest': manifest, 'review': review, 'texts': texts})};\n")
    (out / "data.js").write_text(data_js, encoding="ascii")
    stats["data_js"] = len(data_js)
    return stats


# ─── site ──────────────────────────────────────────────────────────────────────────────────────

def build(out: Path, offline: bool = True) -> list[str]:
    out.mkdir(parents=True, exist_ok=True)
    copied = []
    for name in FILES:
        shutil.copy2(HERE / name, out / name)
        copied.append(name)
    for d in DIRS:
        dst = out / d
        if dst.name in DATA_NAMES:
            raise RuntimeError(f"refusing to overwrite data dir {dst}")
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(HERE / d, dst, ignore=shutil.ignore_patterns("*.map", ".*", "bundle.js"))
        copied += [str(p.relative_to(out)) for p in sorted(dst.rglob("*")) if p.is_file()]
    if offline:
        (out / "js" / "bundle.js").write_text(make_bundle(HERE / "js"), encoding="utf-8")
        shutil.copy2(HERE / "serve.py", out / "serve.py")
        shutil.copy2(HERE / "README.site.txt", out / "README.txt")
        copied += ["js/bundle.js", "serve.py", "README.txt"]
    else:
        for stale in ("data.js", "serve.py", "README.txt"):
            (out / stale).unlink(missing_ok=True)
        if (out / "offline").is_dir():
            shutil.rmtree(out / "offline")
    # GitHub Pages: serve files starting with "_" etc. as-is.
    (out / ".nojekyll").touch()
    return copied


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", required=True, type=Path, help="site root (the render step's OUT dir)")
    ap.add_argument("--no-offline", action="store_true",
                    help="skip the file:// support files (data.js, js/bundle.js, offline/, serve.py, README.txt)")
    args = ap.parse_args(argv)
    try:
        copied = build(args.out, offline=not args.no_offline)
        stats = build_offline(args.out) if not args.no_offline else None
    except (OSError, ValueError) as e:
        print(f"build_site: failed: {e}", file=sys.stderr)
        return 1
    print(f"build_site: copied {len(copied)} viewer files into {args.out}")
    if stats:
        print(f"build_site: file:// support: data.js {stats['data_js'] / 1024:.0f} KiB, "
              f"{stats['packs']} 3D pack(s) {stats['pack_bytes'] / 1024:.0f} KiB"
              + (f", skipped (too large): {', '.join(stats['skipped'])}" if stats["skipped"] else ""))
    if not (args.out / "manifest.json").exists():
        print(f"build_site: warning: {args.out}/manifest.json not found; the viewer will show an error page", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
