#!/usr/bin/env python3
"""Copy an UNTRUSTED review artifact into a clean site directory.

The `component-review` artifact is produced by code from the pull request (which may be a
fork), so before it is published on the repo's GitHub Pages origin we:

  * keep only data files with allow-listed extensions (no HTML/JS/CSS: the viewer is copied
    in afterwards from the trusted default-branch checkout by viewer/build_site.py);
  * drop symlinks, odd names, oversized files and anything outside the tree;
  * drop SVGs containing active content (scripts, event handlers, foreignObject, external refs);
  * drop review.json / review.md (the publish job regenerates them with trusted code);
  * require manifest.json to be valid JSON.

Usage: sanitize_site.py --src UNTRUSTED_DIR --dst CLEAN_DIR
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import SLUG_RE, log  # noqa: E402

ALLOWED_EXT = {
    ".json", ".png", ".jpg", ".jpeg", ".webp", ".svg", ".glb", ".patch", ".diff",
    ".kicad_mod", ".kicad_sym", ".pdf", ".txt", ".csv", ".step", ".stp", ".wrl",
}
DROP_NAMES = {"review.json", "review.md"}   # regenerated by the trusted publish job
MAX_FILE = 30 * 1024 * 1024
MAX_TOTAL = 700 * 1024 * 1024
MAX_FILES = 10000
MAX_DEPTH = 6

SVG_BAD = re.compile(
    rb"<\s*(script|foreignObject|iframe|embed|object|handler|listener)\b"
    rb"|\son[a-z]+\s*="
    rb"|javascript:|vbscript:"
    rb"|<!ENTITY"
    rb"|(?:xlink:)?href\s*=\s*[\"'](?!#|data:image/(?:png|jpeg|gif|webp);)"
    rb"|url\(\s*[\"']?(?!#|data:image/(?:png|jpeg|gif|webp);)"
    rb"|@import",
    re.IGNORECASE,
)


def svg_is_safe(data: bytes) -> bool:
    return SVG_BAD.search(data) is None


def sanitize(src: Path, dst: Path) -> dict:
    if dst.exists():
        shutil.rmtree(dst)
    dst.mkdir(parents=True)
    stats = {"kept": 0, "dropped": [], "bytes": 0}

    def drop(rel: str, why: str) -> None:
        stats["dropped"].append(f"{rel}: {why}")

    src = src.resolve()
    for p in sorted(src.rglob("*")):
        rel_parts = p.relative_to(src).parts
        rel = "/".join(rel_parts)
        if p.is_symlink():
            drop(rel, "symlink")
            continue
        if p.is_dir():
            continue
        if len(rel_parts) > MAX_DEPTH:
            drop(rel, "too deep")
            continue
        if any(not SLUG_RE.fullmatch(part) or part.startswith(".") for part in rel_parts):
            drop(rel, "bad name")
            continue
        name = rel_parts[-1]
        ext = Path(name).suffix.lower()
        if name in DROP_NAMES and len(rel_parts) == 1:
            drop(rel, "regenerated by trusted job")
            continue
        if ext not in ALLOWED_EXT:
            drop(rel, f"extension {ext or '(none)'} not allowed")
            continue
        if len(rel_parts) > 1 and rel_parts[0] != "items":
            drop(rel, "outside items/")
            continue
        size = p.stat().st_size
        if size > MAX_FILE:
            drop(rel, f"too large ({size} bytes)")
            continue
        if stats["bytes"] + size > MAX_TOTAL or stats["kept"] >= MAX_FILES:
            drop(rel, "site size/file-count budget exceeded")
            continue
        data = p.read_bytes()
        if ext == ".svg" and not svg_is_safe(data):
            drop(rel, "svg with active/external content")
            continue
        if ext == ".json":
            try:
                json.loads(data)
            except ValueError:
                drop(rel, "invalid json")
                continue
        out = dst / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(data)
        stats["kept"] += 1
        stats["bytes"] += size

    if not (dst / "manifest.json").is_file():
        raise SystemExit("sanitize: artifact has no valid manifest.json")
    return stats


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--src", required=True, type=Path)
    ap.add_argument("--dst", required=True, type=Path)
    a = ap.parse_args(argv)
    stats = sanitize(a.src, a.dst)
    log(f"sanitize: kept {stats['kept']} files ({stats['bytes']} bytes), dropped {len(stats['dropped'])}")
    for d in stats["dropped"][:200]:
        log(f"  dropped {d}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
