#!/usr/bin/env python3
"""Copy an UNTRUSTED review artifact into a clean site directory.

The `component-review` artifact is produced by code from the pull request (which may be a
fork), so before it is published on the repo's GitHub Pages origin we:

  * keep only data files with allow-listed extensions (no HTML/JS/CSS: the viewer is copied
    in afterwards from the trusted default-branch checkout by viewer/build_site.py);
  * drop symlinks, odd names, oversized files and anything outside the tree;
  * drop SVGs containing active content (scripts, event handlers, foreignObject, external refs);
  * cap file sizes (STEP models 25 MB, PDFs 30 MB, others 10 MB) and the whole site
    (CR_MAX_SITE_MB, default 300 MB; essentials first, bulky STEP/PDF files dropped first);
  * null out manifest references to anything dropped (+ an item warning saying why);
  * drop review.json / review.md (the publish job regenerates them with trusted code);
  * require manifest.json to be valid JSON.

Usage: sanitize_site.py --src UNTRUSTED_DIR --dst CLEAN_DIR
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import SLUG_RE, log  # noqa: E402

ALLOWED_EXT = {
    ".json", ".png", ".jpg", ".jpeg", ".webp", ".svg", ".glb", ".patch", ".diff",
    ".kicad_mod", ".kicad_sym", ".pdf", ".txt", ".csv", ".step", ".stp", ".wrl",
}
DROP_NAMES = {"review.json", "review.md"}   # regenerated by the trusted publish job
MB = 1024 * 1024
# per-file caps by extension (bytes); anything else gets DEFAULT_MAX_FILE
MAX_FILE_BY_EXT = {".step": 25 * MB, ".stp": 25 * MB, ".wrl": 25 * MB, ".glb": 25 * MB, ".pdf": 30 * MB}
DEFAULT_MAX_FILE = 10 * MB
MAX_TOTAL = int(os.environ.get("CR_MAX_SITE_MB", "300")) * MB   # whole site (one PR preview)
MAX_FILES = 10000
MAX_DEPTH = 6
# Admission order when the site budget is tight: small essentials first, bulky 3D/PDF last.
PRIORITY = {".json": 0, ".png": 1, ".svg": 1, ".patch": 2, ".diff": 2, ".kicad_mod": 2, ".kicad_sym": 2,
            ".jpg": 3, ".jpeg": 3, ".webp": 3, ".txt": 3, ".csv": 3, ".step": 5, ".stp": 5, ".wrl": 5,
            ".glb": 6, ".pdf": 7}

SVG_BAD = re.compile(
    rb"<\s*(script|foreignObject|iframe|embed|object|handler|listener)\b"
    rb"|\son[a-z]+\s*="
    rb"|javascript:|vbscript:"
    rb"|<!ENTITY"
    rb"|(?:xlink:)?href\s*=\s*[\"'](?!#|data:image/(?:png|jpeg|gif|webp);)"
    rb"|url\(\s*[\"']?(?!#|data:image/(?:png|jpeg|gif|webp);)"
    rb"|@import",
    re.IGNORECASE,
)
STEP_MAGIC = b"ISO-10303-21"


def svg_is_safe(data: bytes) -> bool:
    return SVG_BAD.search(data) is None


def _null_dropped(node, dropped: dict[str, str], hits: list[str]):
    """Replace every string in the manifest that names a dropped file with None."""
    if isinstance(node, dict):
        return {k: _null_dropped(v, dropped, hits) for k, v in node.items()}
    if isinstance(node, list):
        return [_null_dropped(v, dropped, hits) for v in node]
    if isinstance(node, str) and node in dropped:
        hits.append(node)
        return None
    return node


def fix_manifest(dst: Path, dropped: dict[str, str]) -> int:
    """Null out manifest references to files we dropped and record why in the item's warnings,
    so the viewer/comment show "missing" instead of a broken link."""
    path = dst / "manifest.json"
    manifest = json.loads(path.read_text(encoding="utf-8"))
    items = manifest.get("items") if isinstance(manifest, dict) else None
    if not isinstance(items, list) or not dropped:
        return 0
    n = 0
    for i, item in enumerate(items):
        if not isinstance(item, dict):
            continue
        hits: list[str] = []
        items[i] = item = _null_dropped(item, dropped, hits)
        if hits:
            n += len(hits)
            warns = item.get("warnings") if isinstance(item.get("warnings"), list) else []
            item["warnings"] = warns + [f"ci: {h} not published ({dropped[h]})" for h in sorted(set(hits))]
    path.write_text(json.dumps(manifest, indent=1), encoding="utf-8")
    return n


def sanitize(src: Path, dst: Path, max_total: int = MAX_TOTAL) -> dict:
    if dst.exists():
        shutil.rmtree(dst)
    dst.mkdir(parents=True)
    stats = {"kept": 0, "dropped": [], "bytes": 0, "manifest_refs_nulled": 0}
    dropped: dict[str, str] = {}

    def drop(rel: str, why: str) -> None:
        stats["dropped"].append(f"{rel}: {why}")
        dropped[rel] = why

    # pass 1: per-file checks -> candidates
    src = src.resolve()
    candidates = []
    for p in sorted(src.rglob("*")):
        rel_parts = p.relative_to(src).parts
        rel = "/".join(rel_parts)
        if p.is_symlink():
            drop(rel, "symlink")
            continue
        if p.is_dir():
            continue
        if len(rel_parts) > MAX_DEPTH:
            drop(rel, "too deep")
            continue
        if any(not SLUG_RE.fullmatch(part) or part.startswith(".") for part in rel_parts):
            drop(rel, "bad name")
            continue
        name = rel_parts[-1]
        ext = Path(name).suffix.lower()
        if name in DROP_NAMES and len(rel_parts) == 1:
            drop(rel, "regenerated by trusted job")
            continue
        if ext not in ALLOWED_EXT:
            drop(rel, f"extension {ext or '(none)'} not allowed")
            continue
        if len(rel_parts) > 1 and rel_parts[0] != "items":
            drop(rel, "outside items/")
            continue
        size = p.stat().st_size
        cap = MAX_FILE_BY_EXT.get(ext, DEFAULT_MAX_FILE)
        if size > cap:
            drop(rel, f"too large ({size // MB} MB > {cap // MB} MB cap)")
            continue
        candidates.append((0 if rel == "manifest.json" else 1, PRIORITY.get(ext, 4), size, rel, p, ext))

    # pass 2: admit within the site budget, essentials first
    for _m, _prio, size, rel, p, ext in sorted(candidates):
        if stats["bytes"] + size > max_total or stats["kept"] >= MAX_FILES:
            drop(rel, f"site size budget ({max_total // MB} MB) exceeded")
            continue
        data = p.read_bytes()
        if len(data) != size:
            drop(rel, "changed while reading")
            continue
        if ext == ".svg" and not svg_is_safe(data):
            drop(rel, "svg with active/external content")
            continue
        if ext in (".step", ".stp") and STEP_MAGIC not in data[:256]:
            drop(rel, "not a STEP file")
            continue
        if ext == ".json":
            try:
                json.loads(data)
            except ValueError:
                drop(rel, "invalid json")
                continue
        out = dst / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(data)
        stats["kept"] += 1
        stats["bytes"] += size

    if not (dst / "manifest.json").is_file():
        raise SystemExit("sanitize: artifact has no valid manifest.json")
    stats["manifest_refs_nulled"] = fix_manifest(dst, dropped)
    return stats


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--src", required=True, type=Path)
    ap.add_argument("--dst", required=True, type=Path)
    ap.add_argument("--max-site-mb", type=int, default=MAX_TOTAL // MB)
    a = ap.parse_args(argv)
    stats = sanitize(a.src, a.dst, a.max_site_mb * MB)
    log(f"sanitize: kept {stats['kept']} files ({stats['bytes']} bytes), dropped {len(stats['dropped'])}, "
        f"nulled {stats['manifest_refs_nulled']} manifest reference(s)")
    for d in stats["dropped"][:200]:
        log(f"  dropped {d}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
